# Generated by Django 5.1.4 on 2024-12-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0002_followinginteraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followinginteraction",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followees",
                to="social_network.profile",
            ),
        ),
    ]
