# Generated by Django 5.1.4 on 2024-12-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0004_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="social_network.hashtag"
            ),
        ),
    ]
