# Generated by Django 5.1.4 on 2025-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0008_alter_post_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sheduled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
